src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotNull
     * @var string
     */
    protected $deliveryCountry;

    /**
     * @var string
     * @Assert\NotNull
     * @ORM\Column(type="string")
     */
    protected $deliveryCity;

    /**
     * @var string
     * @Assert\NotNull
     * @ORM\Column(type="string")
     */
    protected $deliveryZip;

    /**
     * @var string
     * @Assert\NotNull
     * @ORM\Column(type="string")
     */
    protected $mail_vendeur;

    /**
     * @var string
     * @Assert\NotNull
     * @ORM\Column(type="string")
     */
    protected $nom_vendeur;

    /**
     * @var int
     * @Assert\NotNull
     * @ORM\Column(type="integer")
     */
    protected $code_command;

    /**
     * @return int
     */
    public function getCodeCommand()
    {
        return $this->code_command;
    }

    /**
     * @param int $code_command
     */
    public function setCodeCommand(int $code_command)
    {
        $this->code_command = $code_command;
    }

    /**
     * @return string
     */
    public function getMailVendeur()
    {
        return $this->mail_vendeur;
    }

    /**
     * @param string $mail_vendeur
     * @return Commande
     */
    public function setMailVendeur(string $mail_vendeur)
    {
        $this->mail_vendeur = $mail_vendeur;
        return $this;
    }

    /**
     * @return string
     */
    public function getNomVendeur()
    {
        return $this->nom_vendeur;
    }

    /**
     * @param string $nom_vendeur
     * @return Commande
     */
    public function setNomVendeur(string $nom_vendeur)
    {
        $this->nom_vendeur = $nom_vendeur;
        return $this;
    }

    /**
     * @var string
     * @Assert\NotNull
     * @ORM\Column(type="string")
     */
    protected $deliveryAddress;

    /**
     * @return string
     */
    public function getDeliveryCountry()
    {
        return $this->deliveryCountry;
    }

    /**
     * @param string $deliveryCountry
     */
    public function setDeliveryCountry(string $deliveryCountry)
    {
        $this->deliveryCountry = $deliveryCountry;
    }

    /**
     * @return string
     */
    public function getDeliveryCity()
    {
        return $this->deliveryCity;
    }

    /**
     * @param string $deliveryCity
     */
    public function setDeliveryCity(string $deliveryCity)
    {
        $this->deliveryCity = $deliveryCity;
    }

    /**
     * @return string
     */
    public function getDeliveryZip()
    {
        return $this->deliveryZip;
    }

    /**
     * @param string $deliveryZip
     */
    public function setDeliveryZip(string $deliveryZip)
    {
        $this->deliveryZip = $deliveryZip;
    }

    /**
     * @return string
     */
    public function getDeliveryAddress()
    {
        return $this->deliveryAddress;
    }

    /**
     * @param string $deliveryAddress
     */
    public function setDeliveryAddress(string $deliveryAddress)
    {
        $this->deliveryAddress = $deliveryAddress;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCommande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modeLivraison;

    /**
     * @ORM\Column(type="integer")
     */
    private $qte;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prixArticleCommande;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $fraisPort;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commandes")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="commande")
     */
    private $article;

    /**
     * @return mixed
     */
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * @param mixed $article
     */
    public function setArticle($article)
    {
        $this->article = $article;
    }



    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->dateCommande;
    }

    public function setDateCommande(\DateTimeInterface $dateCommande): self
    {
        $this->dateCommande = $dateCommande;

        return $this;
    }

    public function getModeLivraison(): ?string
    {
        return $this->modeLivraison;
    }

    public function setModeLivraison(string $modeLivraison): self
    {
        $this->modeLivraison = $modeLivraison;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getPrixArticleCommande(): ?string
    {
        return $this->prixArticleCommande;
    }

    public function setPrixArticleCommande(string $prixArticleCommande): self
    {
        $this->prixArticleCommande = $prixArticleCommande;

        return $this;
    }

    public function getFraisPort(): ?string
    {
        return $this->fraisPort;
    }

    public function setFraisPort(string $fraisPort): self
    {
        $this->fraisPort = $fraisPort;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('etat')
            ->add('dateCommande')
            ->add('modeLivraison')
            ->add('qte')
            ->add('prixArticleCommande')
            ->add('fraisPort')
            ->add('user')
            ->add('cart')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Commande;
use App\Entity\User;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Nelmio\ApiDocBundle\Annotation\Model;
use Nelmio\ApiDocBundle\Annotation\Security;
use Swagger\Annotations as SWG;
use Nelmio\ApiDocBundle\Annotation as Doc;

/**
 * @Route("/commande")
 */
class CommandeController extends AbstractController
{
    /**
     * @Route("/", name="commande_index", methods={"GET"})
     */
    public function index(CommandeRepository $commandeRepository): Response
    {
        $currentUser = $this->getUser();
        if(!$this->getUser())
        {
            return $this->redirectToRoute('home');
        }
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findBy([
                'user'=> $currentUser
            ]),
        ]);
    }

    /**
     * @Route("/facture/{id}", name="commande_facture", methods={"GET"})
     */
    public function facture($id, Pdf $pdf)
    {
        $factures = $this->getDoctrine()->getRepository(Commande::class)->findBy([
            'code_command' => $id
        ]);

        $facture = $this->getDoctrine()->getRepository(Commande::class)->findOneBy([
            'code_command' => $id
        ]);
        $html = $this->renderView('invoice/index.html.twig', array(
            'facture' => $facture,
            'factures'  => $factures,
        ));

        return new PdfResponse(
            $pdf->getOutputFromHtml($html),
            'facture.pdf'
        );
    }

    /**
     * @Route("/api/getAllCommandes", name="apiGetAllCommandes", methods={"GET"})
     * @SWG\Response(
     *     response=200,
     *     description="Retourne la liste des commandes",
     *
     * )
     *
     * @SWG\Tag(name="Commande")
     */
    public function apiGetAllCommandes()
    {
        $commandes = $this->getDoctrine()->getRepository(Commande::class)->findAll();

        $arrayCollection = [];

        /** @var Commande $item */
        foreach($commandes as $item) {
            $arrayCollection[] = array(
                'id' => $item->getId(),
                'etat' => $item->getEtat(),
                'date_commande' => $item->getDateCommande(),
                'mode_livraison' => $item->getModeLivraison(),
                'qte' => $item->getQte(),
                'prix_article_commande' => $item->getPrixArticleCommande(),
                'frais_port' => $item->getFraisPort(),
                'delivery_country' => $item->getDeliveryCountry(),
                'delivery_city' => $item->getDeliveryCity(),
                'delivery_zip' => $item->getDeliveryZip(),
                'delivery_address' => $item->getDeliveryAddress(),
                'mail_vendeur' => $item->getMailVendeur(),
                'nom_vendeur' => $item->getNomVendeur(),
                'code_command' => $item->getCodeCommand()
            );
        }
        return new JsonResponse($arrayCollection);
    }

    /**
     * @Route("/api/apiGetCommandeByUserId/{id}", name="apiGetCommandeByUserId", methods={"GET"})
     * @SWG\Response(
     *     response=200,
     *     description="Retourne la liste des commandes de l'utilisateur",
     *
     * )
     *
     * @SWG\Response(
     *     response=404,
     *     description="Retourne user_not_found",
     *
     * )
     *
     * @SWG\Tag(name="Commande")
     */
    public function apiGetCommandeByUserId($id)
    {

        $user = $this->getDoctrine()->getRepository(User::class)->find($id);

        if(!$user)
        {
            return new JsonResponse([
                'status' => 'user_not_found'
            ], 404);
        }

        $commandes = $this->getDoctrine()->getRepository(Commande::class)->findBy([
            'user' => $user
        ]);

        $arrayCollection = [];

        $currentCommandId = 0;

        /** @var Commande $item */
        foreach($commandes as $item) {
            if($currentCommandId !== $item->getCodeCommand()) {
                $arrayCollection[] = array(
                    'id' => $item->getId(),
                    'etat' => $item->getEtat(),
                    'date_commande' => $item->getDateCommande()->format('d-m-Y'),
                    'mode_livraison' => $item->getModeLivraison(),
                    'qte' => $item->getQte(),
                    'prix_article_commande' => $item->getPrixArticleCommande(),
                    'frais_port' => $item->getFraisPort(),
                    'delivery_country' => $item->getDeliveryCountry(),
                    'delivery_city' => $item->getDeliveryCity(),
                    'delivery_zip' => $item->getDeliveryZip(),
                    'delivery_address' => $item->getDeliveryAddress(),
                    'mail_vendeur' => $item->getMailVendeur(),
                    'nom_vendeur' => $item->getNomVendeur(),
                    'code_command' => $item->getCodeCommand()
                );

                $currentCommandId = $item->getCodeCommand();
            }
        }
        return new JsonResponse($arrayCollection);
    }

    /**
     * @Route("/api/getCommande/{code_command}", name="apiGetCommande", methods={"GET"})
     * @SWG\Response(
     *     response=200,
     *     description="Retourne la commande correspondant au code commande",
     *
     * )
     * @SWG\Response(
     *     response=404,
     *     description="Retourne commande_not_found",
     *
     * )
     *
     * @SWG\Tag(name="Commande")
     */
    public function apiGetCommande($code_command)
    {
        $commande = $this->getDoctrine()->getRepository(Commande::class)->findBy(['code_command' => $code_command]);

        if(!$commande)
        {
            return new JsonResponse(array(
                'status' => 'commande_not_found'
            ), 404);
        }

        $arrayCollection = [];

        /** @var Commande $item */
        foreach($commande as $item) {
            $arrayCollection[] = array(
                'id' => $item->getId(),
                'etat' => $item->getEtat(),
                'date_commande' => $item->getDateCommande(),
                'mode_livraison' => $item->getModeLivraison(),
                'qte' => $item->getQte(),
                'prix_article_commande' => $item->getPrixArticleCommande(),
                'frais_port' => $item->getFraisPort(),
                'delivery_country' => $item->getDeliveryCountry(),
                'delivery_city' => $item->getDeliveryCity(),
                'delivery_zip' => $item->getDeliveryZip(),
                'delivery_address' => $item->getDeliveryAddress(),
                'mail_vendeur' => $item->getMailVendeur(),
                'nom_vendeur' => $item->getNomVendeur(),
                'code_command' => $item->getCodeCommand()
            );
        }

        return new JsonResponse($arrayCollection);
    }

    /**
     * @Route("/api/createCommande", name="apiCreateCommande", methods={"POST"})
     *
     */
    public function apiCreateCommande(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        /** @var Commande $code_command */
        $code_command = $this->getDoctrine()->getRepository(Commande::class)->findLast();

        foreach ($_POST as $produit) {


            $commande = new Commande();

            /** @var Article $article */
            $article = $this->getDoctrine()->getRepository(Article::class)->find($produit['id']);

            $article->setQteEnStock($article->getQteEnStock() - $produit['qty']);

            $commande->setEtat('Commandé');
            $commande->setDateCommande(new \DateTime());
            $commande->setModeLivraison('Chronopost');
            $commande->setQte($produit['qty']);
            $commande->setPrixArticleCommande($article->getPrixUnitaire());
            $commande->setFraisPort(20);
            $commande->setDeliveryCountry($produit['country']);
            $commande->setDeliveryCity($produit['city']);
            $commande->setDeliveryZip($produit['zip']);
            $commande->setDeliveryAddress($produit['address']);
            $commande->setMailVendeur($produit['mailVendeur']);
            $commande->setNomVendeur($produit['nomVendeur']);

            $commande->setUser( $this->getUser());

            $commande->setArticle($article);




            if ($code_command) {
                $commande->setCodeCommand($code_command->getCodeCommand() + 1);
            } else {
                $commande->setCodeCommand(1);
            }


            $arrayCollection[] = array(
                'id' => $commande->getId(),
                'etat' => $commande->getEtat(),
                'date_commande' => $commande->getDateCommande(),
                'mode_livraison' => $commande->getModeLivraison(),
                'qte' => $commande->getQte(),
                'prix_article_commande' => $commande->getPrixArticleCommande(),
                'frais_port' => $commande->getFraisPort(),
                'delivery_country' => $commande->getDeliveryCountry(),
                'delivery_city' => $commande->getDeliveryCity(),
                'delivery_zip' => $commande->getDeliveryZip(),
                'delivery_address' => $commande->getDeliveryAddress(),
                'mail_vendeur' => $commande->getMailVendeur(),
                'nom_vendeur' => $commande->getNomVendeur(),
                'code_command' => $commande->getCodeCommand()
            );
            $entityManager->persist($article);
            $entityManager->persist($commande);
        }

        $entityManager->flush();

        if ($code_command) {

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commande/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commande/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commande{% endblock %}

{% block body %}
    <h1>Edit Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commande_index') }}">back to list</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}

    <link href="{{ asset('css/Command.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <div class="user-flex">
        <div class="user-setting">
            <div class="user-img">
                <img src="{{ asset('icon/user.png') }}"/>
            </div>
            <p>Bonjour</p>
            <p class="name">{{ app.user.username }}</p>
            <div class="disconnect">
                <a href="/logout">ME DÉCONNECTER</a>
            </div>
            <div class="information-setting" onclick="window.location.href ='/user/user' ">
                <p style="margin: auto;">Mes informations</p>
            </div>
            <div class="information-commandes">
                <p style="margin: auto;">Mes commandes</p>
            </div>
        </div>
        <div class="user-info">

{#            {% set currentCommandId = 0 %}#}
{#            {% for commande in commandes %}#}
{#                {% if currentCommandId is not same as (commande.codeCommand) %}#}
{#                    <div class="pdf-block">#}
{#                        <a class="pdf-text">Commande du {{ commande.dateCommande ? commande.dateCommande|date('Y-m-d H:i:s') : '' }}</a>#}
{#                        <a class="pdf" href="/commande/facture/{{ commande.codeCommand }}"#}
{#                           download><span>Download</span><span>PDF</span></a>#}
{#                    </div>#}
{#                    {% set currentCommandId = commande.codeCommand %}#}
{#                {% endif %}#}
{#            {% endfor %}#}

        </div><!-- /.container -->
    </div>

    <script>
        $('#update').click(function () {
            var data = {
                'email': $('#email').val(),
                'username': $('#username').val()
            };


        })
        $.ajax({
            type: "GET",
            url: '/commande/api/apiGetCommandeByUserId/{{ app.user.id }}',
            success: function (data) {
                console.log(data);
                data.forEach(element => {
                    $('.user-info').append(" <div class=\"pdf-block\">\n" +
                        "                        <a class=\"pdf-text\">Commande du "+element.date_commande+"</a>\n" +
                        "                        <a class=\"pdf\" href=\"/commande/facture/"+element.code_command+"\"\n" +
                        "                           download><span>Download</span><span>PDF</span></a>\n" +
                        "                    </div>")
                })
            }
        });
    </script>
{% endblock %}

templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block body %}
    <h1>Create new Commande</h1>

    {{ include('commande/_form.html.twig') }}

    <a href="{{ path('commande_index') }}">back to list</a>
{% endblock %}

templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>
    {% set price = 0 %}

   {% for commande in commandes %}
        {{ commande.article.nom }}
       {% set price = price + commande.prixArticleCommande * commande.qte %}
    {% endfor %}

    {% set price = price + 20 %}

    Frais de port : 20€

    Lieu de livraison: {{ address }} {{ city }} {{ zip }} {{ country }}

    Etat de commande : {{ etat }}

    Total: {{ price }} €

    <a href="{{ path('commande_index') }}">back to list</a>

{% endblock %}